{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Involute Gear Tooth Profile Generator\n",
    "\n",
    "This notebook generates accurate involute gear tooth profiles with configurable parameters.\n",
    "Features:\n",
    "- Mathematical generation of involute curves\n",
    "- Complete gear profile with all teeth\n",
    "- Matplotlib visualization\n",
    "- DXF export for CAD software"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Import Required Libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.patches import Polygon\n",
    "import math\n",
    "from dataclasses import dataclass\n",
    "from typing import Tuple, List\n",
    "import ezdxf\n",
    "from ezdxf import colors\n",
    "from IPython.display import display, HTML"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Gear Parameters Configuration\n",
    "\n",
    "Easily configure your gear parameters here:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@dataclass\n",
    "class GearParameters:\n",
    "    \"\"\"Configurable parameters for involute gear generation\"\"\"\n",
    "    \n",
    "    # Basic Parameters\n",
    "    number_of_teeth: int = 20          # Number of teeth (z)\n",
    "    module: float = 5.0                 # Module (m) in mm - determines tooth size\n",
    "    pressure_angle_deg: float = 20.0    # Pressure angle in degrees (typically 20° or 25°)\n",
    "    \n",
    "    # Addendum and Dedendum factors (standard values)\n",
    "    addendum_factor: float = 1.0        # Addendum = addendum_factor * module\n",
    "    dedendum_factor: float = 1.25       # Dedendum = dedendum_factor * module\n",
    "    \n",
    "    # Profile Shift (0 for standard gears)\n",
    "    profile_shift: float = 0.0          # Profile shift coefficient (x)\n",
    "    \n",
    "    # Tooth thickness factor\n",
    "    backlash: float = 0.0               # Backlash in mm\n",
    "    \n",
    "    # Fillet radius factor\n",
    "    fillet_radius_factor: float = 0.38  # Fillet radius = factor * module\n",
    "    \n",
    "    # Resolution for curves\n",
    "    points_per_curve: int = 50          # Number of points for involute curve\n",
    "    \n",
    "    # Display options\n",
    "    show_pitch_circle: bool = True\n",
    "    show_base_circle: bool = True\n",
    "    show_addendum_circle: bool = True\n",
    "    show_dedendum_circle: bool = True\n",
    "    \n",
    "    def __post_init__(self):\n",
    "        \"\"\"Calculate derived parameters\"\"\"\n",
    "        self.pressure_angle = math.radians(self.pressure_angle_deg)\n",
    "        self.pitch_diameter = self.module * self.number_of_teeth\n",
    "        self.pitch_radius = self.pitch_diameter / 2\n",
    "        self.base_radius = self.pitch_radius * math.cos(self.pressure_angle)\n",
    "        self.addendum = self.addendum_factor * self.module\n",
    "        self.dedendum = self.dedendum_factor * self.module\n",
    "        self.addendum_radius = self.pitch_radius + self.addendum\n",
    "        self.dedendum_radius = self.pitch_radius - self.dedendum\n",
    "        self.tooth_thickness = (math.pi * self.module / 2) - self.backlash\n",
    "        self.angular_pitch = 2 * math.pi / self.number_of_teeth\n",
    "\n",
    "# Create default gear parameters\n",
    "gear_params = GearParameters()\n",
    "print(f\"Gear Configuration:\")\n",
    "print(f\"  Number of teeth: {gear_params.number_of_teeth}\")\n",
    "print(f\"  Module: {gear_params.module} mm\")\n",
    "print(f\"  Pressure angle: {gear_params.pressure_angle_deg}°\")\n",
    "print(f\"  Pitch diameter: {gear_params.pitch_diameter:.2f} mm\")\n",
    "print(f\"  Base circle diameter: {gear_params.base_radius * 2:.2f} mm\")\n",
    "print(f\"  Addendum circle diameter: {gear_params.addendum_radius * 2:.2f} mm\")\n",
    "print(f\"  Dedendum circle diameter: {gear_params.dedendum_radius * 2:.2f} mm\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Involute Curve Generation Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def involute_point(base_radius: float, angle: float) -> Tuple[float, float]:\n",
    "    \"\"\"\n",
    "    Calculate a point on the involute curve.\n",
    "    \n",
    "    Args:\n",
    "        base_radius: Base circle radius\n",
    "        angle: Unwrap angle in radians\n",
    "    \n",
    "    Returns:\n",
    "        (x, y) coordinates of the involute point\n",
    "    \"\"\"\n",
    "    x = base_radius * (math.cos(angle) + angle * math.sin(angle))\n",
    "    y = base_radius * (math.sin(angle) - angle * math.cos(angle))\n",
    "    return x, y\n",
    "\n",
    "def generate_involute_curve(gear_params: GearParameters) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Generate the involute curve from base circle to addendum circle.\n",
    "    \n",
    "    Args:\n",
    "        gear_params: Gear parameters\n",
    "    \n",
    "    Returns:\n",
    "        Array of (x, y) points defining the involute curve\n",
    "    \"\"\"\n",
    "    # Calculate the angle range for the involute\n",
    "    # Start angle (at base circle)\n",
    "    theta_start = 0\n",
    "    \n",
    "    # End angle (at addendum circle)\n",
    "    # Using the relationship: r = r_b * sqrt(1 + theta^2)\n",
    "    theta_end = math.sqrt((gear_params.addendum_radius / gear_params.base_radius) ** 2 - 1)\n",
    "    \n",
    "    # Generate points along the involute\n",
    "    theta_values = np.linspace(theta_start, theta_end, gear_params.points_per_curve)\n",
    "    points = []\n",
    "    \n",
    "    for theta in theta_values:\n",
    "        x, y = involute_point(gear_params.base_radius, theta)\n",
    "        points.append([x, y])\n",
    "    \n",
    "    return np.array(points)\n",
    "\n",
    "def rotate_points(points: np.ndarray, angle: float, center: Tuple[float, float] = (0, 0)) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Rotate points around a center.\n",
    "    \n",
    "    Args:\n",
    "        points: Array of (x, y) points\n",
    "        angle: Rotation angle in radians\n",
    "        center: Center of rotation\n",
    "    \n",
    "    Returns:\n",
    "        Rotated points\n",
    "    \"\"\"\n",
    "    cos_angle = math.cos(angle)\n",
    "    sin_angle = math.sin(angle)\n",
    "    \n",
    "    # Translate to origin\n",
    "    translated = points - np.array(center)\n",
    "    \n",
    "    # Rotate\n",
    "    rotated = np.zeros_like(translated)\n",
    "    rotated[:, 0] = translated[:, 0] * cos_angle - translated[:, 1] * sin_angle\n",
    "    rotated[:, 1] = translated[:, 0] * sin_angle + translated[:, 1] * cos_angle\n",
    "    \n",
    "    # Translate back\n",
    "    return rotated + np.array(center)\n",
    "\n",
    "def mirror_points(points: np.ndarray, axis_angle: float = 0) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Mirror points across an axis passing through the origin.\n",
    "    \n",
    "    Args:\n",
    "        points: Array of (x, y) points\n",
    "        axis_angle: Angle of the mirror axis\n",
    "    \n",
    "    Returns:\n",
    "        Mirrored points\n",
    "    \"\"\"\n",
    "    # Rotate to align axis with x-axis\n",
    "    rotated = rotate_points(points, -axis_angle)\n",
    "    \n",
    "    # Mirror across x-axis\n",
    "    rotated[:, 1] = -rotated[:, 1]\n",
    "    \n",
    "    # Rotate back\n",
    "    return rotate_points(rotated, axis_angle)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Complete Gear Profile Generation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_single_tooth(gear_params: GearParameters) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Generate a single tooth profile.\n",
    "    \n",
    "    Args:\n",
    "        gear_params: Gear parameters\n",
    "    \n",
    "    Returns:\n",
    "        Array of points defining one tooth\n",
    "    \"\"\"\n",
    "    # Generate the involute curve\n",
    "    involute_curve = generate_involute_curve(gear_params)\n",
    "    \n",
    "    # Calculate the angle at the pitch circle\n",
    "    # Find where involute intersects pitch circle\n",
    "    pitch_angle = math.sqrt((gear_params.pitch_radius / gear_params.base_radius) ** 2 - 1)\n",
    "    x_pitch, y_pitch = involute_point(gear_params.base_radius, pitch_angle)\n",
    "    inv_angle_at_pitch = math.atan2(y_pitch, x_pitch)\n",
    "    \n",
    "    # Tooth thickness angle at pitch circle\n",
    "    tooth_angle = gear_params.tooth_thickness / gear_params.pitch_radius\n",
    "    \n",
    "    # Rotation to position the involute correctly\n",
    "    rotation_angle = tooth_angle / 2 - inv_angle_at_pitch\n",
    "    \n",
    "    # Rotate the involute curve\n",
    "    right_side = rotate_points(involute_curve, rotation_angle)\n",
    "    \n",
    "    # Create the left side by mirroring\n",
    "    left_side = mirror_points(right_side)\n",
    "    left_side = left_side[::-1]  # Reverse order\n",
    "    \n",
    "    # Add dedendum circle arc if needed\n",
    "    if gear_params.dedendum_radius < gear_params.base_radius:\n",
    "        # Add root circle arc\n",
    "        angle_start = math.atan2(left_side[0, 1], left_side[0, 0])\n",
    "        angle_end = math.atan2(right_side[0, 1], right_side[0, 0])\n",
    "        \n",
    "        root_arc_angles = np.linspace(angle_start, angle_end, 10)\n",
    "        root_arc = np.array([\n",
    "            [gear_params.dedendum_radius * math.cos(a), \n",
    "             gear_params.dedendum_radius * math.sin(a)] \n",
    "            for a in root_arc_angles\n",
    "        ])\n",
    "        \n",
    "        # Combine: left side + root arc + right side\n",
    "        tooth_profile = np.vstack([left_side, root_arc, right_side])\n",
    "    else:\n",
    "        # Connect involute curves at base circle\n",
    "        tooth_profile = np.vstack([left_side, right_side])\n",
    "    \n",
    "    return tooth_profile\n",
    "\n",
    "def generate_full_gear(gear_params: GearParameters) -> List[np.ndarray]:\n",
    "    \"\"\"\n",
    "    Generate the complete gear with all teeth.\n",
    "    \n",
    "    Args:\n",
    "        gear_params: Gear parameters\n",
    "    \n",
    "    Returns:\n",
    "        List of tooth profiles\n",
    "    \"\"\"\n",
    "    # Generate single tooth\n",
    "    single_tooth = generate_single_tooth(gear_params)\n",
    "    \n",
    "    # Generate all teeth by rotation\n",
    "    teeth = []\n",
    "    for i in range(gear_params.number_of_teeth):\n",
    "        angle = i * gear_params.angular_pitch\n",
    "        rotated_tooth = rotate_points(single_tooth, angle)\n",
    "        teeth.append(rotated_tooth)\n",
    "    \n",
    "    return teeth\n",
    "\n",
    "# Generate the gear\n",
    "gear_teeth = generate_full_gear(gear_params)\n",
    "print(f\"Generated {len(gear_teeth)} teeth\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Visualization with Matplotlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_gear(gear_params: GearParameters, teeth: List[np.ndarray], \n",
    "              figsize: Tuple[float, float] = (12, 12),\n",
    "              save_path: str = None):\n",
    "    \"\"\"\n",
    "    Plot the gear using matplotlib.\n",
    "    \n",
    "    Args:\n",
    "        gear_params: Gear parameters\n",
    "        teeth: List of tooth profiles\n",
    "        figsize: Figure size\n",
    "        save_path: Optional path to save the figure\n",
    "    \"\"\"\n",
    "    fig, ax = plt.subplots(figsize=figsize)\n",
    "    \n",
    "    # Plot teeth\n",
    "    for tooth in teeth:\n",
    "        ax.plot(tooth[:, 0], tooth[:, 1], 'b-', linewidth=2)\n",
    "    \n",
    "    # Plot reference circles if enabled\n",
    "    circle_angles = np.linspace(0, 2 * np.pi, 100)\n",
    "    \n",
    "    if gear_params.show_pitch_circle:\n",
    "        pitch_x = gear_params.pitch_radius * np.cos(circle_angles)\n",
    "        pitch_y = gear_params.pitch_radius * np.sin(circle_angles)\n",
    "        ax.plot(pitch_x, pitch_y, 'g--', linewidth=1, label='Pitch Circle', alpha=0.5)\n",
    "    \n",
    "    if gear_params.show_base_circle:\n",
    "        base_x = gear_params.base_radius * np.cos(circle_angles)\n",
    "        base_y = gear_params.base_radius * np.sin(circle_angles)\n",
    "        ax.plot(base_x, base_y, 'r--', linewidth=1, label='Base Circle', alpha=0.5)\n",
    "    \n",
    "    if gear_params.show_addendum_circle:\n",
    "        add_x = gear_params.addendum_radius * np.cos(circle_angles)\n",
    "        add_y = gear_params.addendum_radius * np.sin(circle_angles)\n",
    "        ax.plot(add_x, add_y, 'm--', linewidth=1, label='Addendum Circle', alpha=0.5)\n",
    "    \n",
    "    if gear_params.show_dedendum_circle:\n",
    "        ded_x = gear_params.dedendum_radius * np.cos(circle_angles)\n",
    "        ded_y = gear_params.dedendum_radius * np.sin(circle_angles)\n",
    "        ax.plot(ded_x, ded_y, 'c--', linewidth=1, label='Dedendum Circle', alpha=0.5)\n",
    "    \n",
    "    # Add center mark\n",
    "    ax.plot(0, 0, 'k+', markersize=10)\n",
    "    \n",
    "    # Set equal aspect ratio and grid\n",
    "    ax.set_aspect('equal')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "    ax.legend(loc='upper right')\n",
    "    \n",
    "    # Labels and title\n",
    "    ax.set_xlabel('X (mm)')\n",
    "    ax.set_ylabel('Y (mm)')\n",
    "    ax.set_title(f'Involute Gear Profile\\n'\n",
    "                f'{gear_params.number_of_teeth} Teeth, '\n",
    "                f'Module = {gear_params.module} mm, '\n",
    "                f'Pressure Angle = {gear_params.pressure_angle_deg}°')\n",
    "    \n",
    "    # Set axis limits\n",
    "    limit = gear_params.addendum_radius * 1.1\n",
    "    ax.set_xlim(-limit, limit)\n",
    "    ax.set_ylim(-limit, limit)\n",
    "    \n",
    "    if save_path:\n",
    "        plt.savefig(save_path, dpi=300, bbox_inches='tight')\n",
    "        print(f\"Figure saved to {save_path}\")\n",
    "    \n",
    "    plt.show()\n",
    "\n",
    "# Plot the gear\n",
    "plot_gear(gear_params, gear_teeth)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. DXF Export Functionality"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def export_to_dxf(gear_params: GearParameters, teeth: List[np.ndarray], \n",
    "                  filename: str = \"gear_profile.dxf\",\n",
    "                  add_circles: bool = True):\n",
    "    \"\"\"\n",
    "    Export the gear profile to DXF format.\n",
    "    \n",
    "    Args:\n",
    "        gear_params: Gear parameters\n",
    "        teeth: List of tooth profiles\n",
    "        filename: Output DXF filename\n",
    "        add_circles: Whether to add reference circles\n",
    "    \"\"\"\n",
    "    # Create a new DXF document\n",
    "    doc = ezdxf.new('R2010')\n",
    "    msp = doc.modelspace()\n",
    "    \n",
    "    # Add teeth as polylines\n",
    "    for tooth in teeth:\n",
    "        # Convert tooth profile to list of tuples\n",
    "        points = [(float(x), float(y)) for x, y in tooth]\n",
    "        \n",
    "        # Create polyline\n",
    "        polyline = msp.add_lwpolyline(points, close=False)\n",
    "        polyline.dxf.color = colors.BLUE\n",
    "        polyline.dxf.lineweight = 50  # 0.5mm lineweight\n",
    "    \n",
    "    # Add reference circles if requested\n",
    "    if add_circles:\n",
    "        # Pitch circle\n",
    "        pitch_circle = msp.add_circle(\n",
    "            center=(0, 0),\n",
    "            radius=gear_params.pitch_radius\n",
    "        )\n",
    "        pitch_circle.dxf.color = colors.GREEN\n",
    "        pitch_circle.dxf.lineweight = 25\n",
    "        \n",
    "        # Base circle\n",
    "        base_circle = msp.add_circle(\n",
    "            center=(0, 0),\n",
    "            radius=gear_params.base_radius\n",
    "        )\n",
    "        base_circle.dxf.color = colors.RED\n",
    "        base_circle.dxf.lineweight = 25\n",
    "        \n",
    "        # Addendum circle\n",
    "        add_circle = msp.add_circle(\n",
    "            center=(0, 0),\n",
    "            radius=gear_params.addendum_radius\n",
    "        )\n",
    "        add_circle.dxf.color = colors.MAGENTA\n",
    "        add_circle.dxf.lineweight = 25\n",
    "        \n",
    "        # Dedendum circle\n",
    "        ded_circle = msp.add_circle(\n",
    "            center=(0, 0),\n",
    "            radius=gear_params.dedendum_radius\n",
    "        )\n",
    "        ded_circle.dxf.color = colors.CYAN\n",
    "        ded_circle.dxf.lineweight = 25\n",
    "    \n",
    "    # Add center point\n",
    "    msp.add_point((0, 0)).dxf.color = colors.WHITE\n",
    "    \n",
    "    # Save the DXF file\n",
    "    doc.saveas(filename)\n",
    "    print(f\"DXF file saved as '{filename}'\")\n",
    "    print(f\"File contains:\")\n",
    "    print(f\"  - {gear_params.number_of_teeth} tooth profiles\")\n",
    "    if add_circles:\n",
    "        print(f\"  - Reference circles (pitch, base, addendum, dedendum)\")\n",
    "    print(f\"  - Center point marker\")\n",
    "    \n",
    "    return filename\n",
    "\n",
    "# Export to DXF\n",
    "dxf_filename = export_to_dxf(gear_params, gear_teeth, \"involute_gear.dxf\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Interactive Gear Generator\n",
    "\n",
    "Modify parameters and regenerate the gear:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_and_display_gear(number_of_teeth=20, module=5.0, pressure_angle_deg=20.0,\n",
    "                             addendum_factor=1.0, dedendum_factor=1.25,\n",
    "                             show_circles=True, export_dxf=False):\n",
    "    \"\"\"\n",
    "    Generate and display a gear with specified parameters.\n",
    "    \n",
    "    This function provides an easy interface for experimenting with different gear parameters.\n",
    "    \"\"\"\n",
    "    # Create gear parameters\n",
    "    params = GearParameters(\n",
    "        number_of_teeth=number_of_teeth,\n",
    "        module=module,\n",
    "        pressure_angle_deg=pressure_angle_deg,\n",
    "        addendum_factor=addendum_factor,\n",
    "        dedendum_factor=dedendum_factor,\n",
    "        show_pitch_circle=show_circles,\n",
    "        show_base_circle=show_circles,\n",
    "        show_addendum_circle=show_circles,\n",
    "        show_dedendum_circle=show_circles\n",
    "    )\n",
    "    \n",
    "    # Generate gear teeth\n",
    "    teeth = generate_full_gear(params)\n",
    "    \n",
    "    # Display gear information\n",
    "    print(\"=\"*50)\n",
    "    print(\"GEAR SPECIFICATIONS\")\n",
    "    print(\"=\"*50)\n",
    "    print(f\"Number of teeth: {params.number_of_teeth}\")\n",
    "    print(f\"Module: {params.module} mm\")\n",
    "    print(f\"Pressure angle: {params.pressure_angle_deg}°\")\n",
    "    print(f\"Pitch diameter: {params.pitch_diameter:.2f} mm\")\n",
    "    print(f\"Base diameter: {params.base_radius * 2:.2f} mm\")\n",
    "    print(f\"Tip diameter: {params.addendum_radius * 2:.2f} mm\")\n",
    "    print(f\"Root diameter: {params.dedendum_radius * 2:.2f} mm\")\n",
    "    print(f\"Circular pitch: {math.pi * params.module:.3f} mm\")\n",
    "    print(f\"Tooth thickness at pitch: {params.tooth_thickness:.3f} mm\")\n",
    "    print(\"=\"*50)\n",
    "    \n",
    "    # Plot the gear\n",
    "    plot_gear(params, teeth)\n",
    "    \n",
    "    # Export to DXF if requested\n",
    "    if export_dxf:\n",
    "        filename = f\"gear_{number_of_teeth}T_m{module}.dxf\"\n",
    "        export_to_dxf(params, teeth, filename)\n",
    "    \n",
    "    return params, teeth\n",
    "\n",
    "# Example: Generate a different gear\n",
    "params2, teeth2 = generate_and_display_gear(\n",
    "    number_of_teeth=30,\n",
    "    module=3.0,\n",
    "    pressure_angle_deg=25.0,\n",
    "    export_dxf=True\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Gear Mesh Visualization\n",
    "\n",
    "Visualize two gears in mesh:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_gear_mesh(params1: GearParameters, params2: GearParameters,\n",
    "                  rotation1: float = 0, rotation2: float = 0):\n",
    "    \"\"\"\n",
    "    Plot two gears in mesh.\n",
    "    \n",
    "    Args:\n",
    "        params1: Parameters for first gear\n",
    "        params2: Parameters for second gear\n",
    "        rotation1: Rotation angle for first gear (radians)\n",
    "        rotation2: Rotation angle for second gear (radians)\n",
    "    \"\"\"\n",
    "    # Check module compatibility\n",
    "    if abs(params1.module - params2.module) > 0.001:\n",
    "        print(\"Warning: Gears have different modules!\")\n",
    "    \n",
    "    # Calculate center distance\n",
    "    center_distance = (params1.pitch_radius + params2.pitch_radius)\n",
    "    \n",
    "    # Generate teeth\n",
    "    teeth1 = generate_full_gear(params1)\n",
    "    teeth2 = generate_full_gear(params2)\n",
    "    \n",
    "    # Apply rotations\n",
    "    teeth1_rotated = [rotate_points(tooth, rotation1) for tooth in teeth1]\n",
    "    teeth2_rotated = [rotate_points(tooth, rotation2) for tooth in teeth2]\n",
    "    \n",
    "    # Translate second gear\n",
    "    teeth2_translated = [tooth + np.array([center_distance, 0]) for tooth in teeth2_rotated]\n",
    "    \n",
    "    # Plot\n",
    "    fig, ax = plt.subplots(figsize=(14, 10))\n",
    "    \n",
    "    # Plot first gear\n",
    "    for tooth in teeth1_rotated:\n",
    "        ax.plot(tooth[:, 0], tooth[:, 1], 'b-', linewidth=2, label='Gear 1' if tooth is teeth1_rotated[0] else '')\n",
    "    \n",
    "    # Plot second gear\n",
    "    for tooth in teeth2_translated:\n",
    "        ax.plot(tooth[:, 0], tooth[:, 1], 'r-', linewidth=2, label='Gear 2' if tooth is teeth2_translated[0] else '')\n",
    "    \n",
    "    # Plot pitch circles\n",
    "    circle_angles = np.linspace(0, 2 * np.pi, 100)\n",
    "    \n",
    "    # Gear 1 pitch circle\n",
    "    pitch1_x = params1.pitch_radius * np.cos(circle_angles)\n",
    "    pitch1_y = params1.pitch_radius * np.sin(circle_angles)\n",
    "    ax.plot(pitch1_x, pitch1_y, 'b--', linewidth=1, alpha=0.3)\n",
    "    \n",
    "    # Gear 2 pitch circle\n",
    "    pitch2_x = params2.pitch_radius * np.cos(circle_angles) + center_distance\n",
    "    pitch2_y = params2.pitch_radius * np.sin(circle_angles)\n",
    "    ax.plot(pitch2_x, pitch2_y, 'r--', linewidth=1, alpha=0.3)\n",
    "    \n",
    "    # Mark centers\n",
    "    ax.plot(0, 0, 'b+', markersize=10)\n",
    "    ax.plot(center_distance, 0, 'r+', markersize=10)\n",
    "    \n",
    "    # Settings\n",
    "    ax.set_aspect('equal')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "    ax.legend(loc='upper right')\n",
    "    ax.set_xlabel('X (mm)')\n",
    "    ax.set_ylabel('Y (mm)')\n",
    "    ax.set_title(f'Gear Mesh Visualization\\n'\n",
    "                f'Gear 1: {params1.number_of_teeth}T, Gear 2: {params2.number_of_teeth}T\\n'\n",
    "                f'Center Distance: {center_distance:.2f} mm')\n",
    "    \n",
    "    plt.show()\n",
    "    \n",
    "    # Print mesh information\n",
    "    gear_ratio = params2.number_of_teeth / params1.number_of_teeth\n",
    "    print(f\"\\nMesh Information:\")\n",
    "    print(f\"  Center distance: {center_distance:.2f} mm\")\n",
    "    print(f\"  Gear ratio: {gear_ratio:.3f} (Gear 2 : Gear 1)\")\n",
    "    print(f\"  Module: {params1.module} mm\")\n",
    "\n",
    "# Create two meshing gears\n",
    "gear1_params = GearParameters(number_of_teeth=15, module=5.0)\n",
    "gear2_params = GearParameters(number_of_teeth=30, module=5.0)\n",
    "\n",
    "# Visualize mesh\n",
    "plot_gear_mesh(gear1_params, gear2_params, rotation1=0, rotation2=math.pi/30)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Batch Export - Generate Multiple Gear Variations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def batch_generate_gears(teeth_range, module_values, pressure_angles, export_dxf=True, export_png=True):\n",
    "    \"\"\"\n",
    "    Generate multiple gear variations for comparison or manufacturing.\n",
    "    \n",
    "    Args:\n",
    "        teeth_range: List or range of tooth counts\n",
    "        module_values: List of module values\n",
    "        pressure_angles: List of pressure angles\n",
    "        export_dxf: Export DXF files\n",
    "        export_png: Export PNG images\n",
    "    \"\"\"\n",
    "    import os\n",
    "    \n",
    "    # Create output directory\n",
    "    os.makedirs('gear_exports', exist_ok=True)\n",
    "    \n",
    "    generated_gears = []\n",
    "    \n",
    "    for teeth in teeth_range:\n",
    "        for module in module_values:\n",
    "            for angle in pressure_angles:\n",
    "                print(f\"\\nGenerating: {teeth}T, Module {module}, Angle {angle}°\")\n",
    "                \n",
    "                # Create gear\n",
    "                params = GearParameters(\n",
    "                    number_of_teeth=teeth,\n",
    "                    module=module,\n",
    "                    pressure_angle_deg=angle\n",
    "                )\n",
    "                \n",
    "                teeth_profile = generate_full_gear(params)\n",
    "                \n",
    "                # Generate filename base\n",
    "                filename_base = f\"gear_{teeth}T_m{module}_a{angle}\"\n",
    "                \n",
    "                # Export DXF\n",
    "                if export_dxf:\n",
    "                    dxf_path = f\"gear_exports/{filename_base}.dxf\"\n",
    "                    export_to_dxf(params, teeth_profile, dxf_path, add_circles=False)\n",
    "                \n",
    "                # Export PNG\n",
    "                if export_png:\n",
    "                    png_path = f\"gear_exports/{filename_base}.png\"\n",
    "                    fig, ax = plt.subplots(figsize=(8, 8))\n",
    "                    for tooth in teeth_profile:\n",
    "                        ax.plot(tooth[:, 0], tooth[:, 1], 'b-', linewidth=2)\n",
    "                    ax.set_aspect('equal')\n",
    "                    ax.grid(True, alpha=0.3)\n",
    "                    ax.set_title(f'{teeth}T, Module {module}, {angle}°')\n",
    "                    plt.savefig(png_path, dpi=150, bbox_inches='tight')\n",
    "                    plt.close()\n",
    "                    print(f\"  Saved: {png_path}\")\n",
    "                \n",
    "                generated_gears.append({\n",
    "                    'params': params,\n",
    "                    'filename_base': filename_base\n",
    "                })\n",
    "    \n",
    "    print(f\"\\n{'='*50}\")\n",
    "    print(f\"Batch generation complete!\")\n",
    "    print(f\"Generated {len(generated_gears)} gear variations\")\n",
    "    print(f\"Files saved in 'gear_exports' directory\")\n",
    "    \n",
    "    return generated_gears\n",
    "\n",
    "# Example batch generation\n",
    "batch_results = batch_generate_gears(\n",
    "    teeth_range=[12, 20, 24],\n",
    "    module_values=[3.0, 5.0],\n",
    "    pressure_angles=[20.0],\n",
    "    export_dxf=True,\n",
    "    export_png=True\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Quick Reference - Common Gear Configurations\n",
    "\n",
    "Here are some quick examples you can run:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Small precision gear\n",
    "small_gear = GearParameters(\n",
    "    number_of_teeth=12,\n",
    "    module=1.0,\n",
    "    pressure_angle_deg=20.0\n",
    ")\n",
    "\n",
    "# Standard gear\n",
    "standard_gear = GearParameters(\n",
    "    number_of_teeth=20,\n",
    "    module=5.0,\n",
    "    pressure_angle_deg=20.0\n",
    ")\n",
    "\n",
    "# High pressure angle gear (stronger teeth)\n",
    "strong_gear = GearParameters(\n",
    "    number_of_teeth=24,\n",
    "    module=4.0,\n",
    "    pressure_angle_deg=25.0\n",
    ")\n",
    "\n",
    "# Large gear for high torque\n",
    "large_gear = GearParameters(\n",
    "    number_of_teeth=60,\n",
    "    module=8.0,\n",
    "    pressure_angle_deg=20.0\n",
    ")\n",
    "\n",
    "# Select which gear to visualize\n",
    "selected_gear = standard_gear  # Change this to try different configurations\n",
    "teeth = generate_full_gear(selected_gear)\n",
    "plot_gear(selected_gear, teeth)\n",
    "\n",
    "# Export the selected gear\n",
    "export_to_dxf(selected_gear, teeth, \"selected_gear.dxf\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary\n",
    "\n",
    "This notebook provides a complete toolkit for generating involute gear profiles with the following features:\n",
    "\n",
    "1. **Configurable Parameters**: Easy adjustment of all gear parameters including number of teeth, module, pressure angle, and more.\n",
    "\n",
    "2. **Accurate Mathematics**: Proper involute curve generation based on gear theory.\n",
    "\n",
    "3. **Visualization**: Clear matplotlib plots with reference circles and customizable display options.\n",
    "\n",
    "4. **DXF Export**: Industry-standard CAD format export for manufacturing.\n",
    "\n",
    "5. **Gear Mesh Visualization**: See how two gears work together.\n",
    "\n",
    "6. **Batch Generation**: Create multiple gear variations efficiently.\n",
    "\n",
    "### Tips for Use:\n",
    "\n",
    "- **Module**: Determines the size of teeth. Larger module = larger teeth.\n",
    "- **Pressure Angle**: Standard values are 20° or 25°. Higher angles give stronger but noisier gears.\n",
    "- **Number of Teeth**: Minimum ~12 teeth to avoid undercutting (depends on pressure angle).\n",
    "- **For Manufacturing**: Export to DXF and import into your CAD software for further refinement.\n",
    "\n",
    "### Next Steps:\n",
    "\n",
    "- Add helical gear support\n",
    "- Implement gear strength calculations\n",
    "- Add internal gear generation\n",
    "- Include backlash and tolerance calculations\n",
    "- Add animation of meshing gears"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}