#!/usr/bin/env python3
Import("env")
import subprocess
import os

def get_git_hash():
    try:
        # Get short git hash
        result = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'],
                              capture_output=True, text=True, check=True,
                              cwd=env.get("PROJECT_DIR"))
        return result.stdout.strip()
    except:
        return "unknown"

def get_git_branch():
    try:
        result = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
                              capture_output=True, text=True, check=True,
                              cwd=env.get("PROJECT_DIR"))
        return result.stdout.strip()
    except:
        return "unknown"

def check_git_dirty():
    try:
        result = subprocess.run(['git', 'status', '--porcelain'],
                              capture_output=True, text=True, check=True,
                              cwd=env.get("PROJECT_DIR"))
        return len(result.stdout.strip()) > 0
    except:
        return False

# Generate build_info.h
git_hash = get_git_hash()
git_branch = get_git_branch()
git_dirty = check_git_dirty()
dirty_suffix = "-dirty" if git_dirty else ""

header_content = f"""// Auto-generated build information
// DO NOT EDIT - This file is automatically generated at build time

#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_GIT_HASH "{git_hash}{dirty_suffix}"
#define BUILD_GIT_BRANCH "{git_branch}"
#define BUILD_TIMESTAMP __DATE__ " " __TIME__

#endif // BUILD_INFO_H
"""

# Write to src directory using project directory from env
project_dir = env.get("PROJECT_DIR")
output_path = os.path.join(project_dir, 'src', 'build_info.h')
with open(output_path, 'w') as f:
    f.write(header_content)

print(f"Generated build_info.h: {git_branch}@{git_hash}{dirty_suffix}")
